# Generated by Django 5.2.1 on 2026-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Journalist", "Journalist"),
                    ("Editor", "Editor"),
                    ("Admin", "Admin"),
                ],
                default="Journalist",
                max_length=20,
            ),
        ),
    ]
