# Generated by Django 5.1.3 on 2026-10-01 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_newslettersubscription_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("tag", "Tag"),
                            ("author", "Author"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["interest_type", "value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "interest_type", "value"),
                        name="unique_reader_interest",
                    )
                ],
            },
        ),
    ]
