# Generated by Django 5.2.1 on 2026-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_articlerevision_notification_article_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scheduled_publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                    ("comment", "Comment"),
                ],
                max_length=20,
            ),
        ),
    ]
