# Generated by Django 5.2.1 on 2026-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
