# Generated by Django 5.2.1 on 2026-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_articleassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
