# Generated by Django 5.2.1 on 2026-09-30 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_featured_at_article_is_featured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleimage",
            options={"ordering": ["sort_order", "created_at"]},
        ),
        migrations.AddField(
            model_name="articleimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="articleimage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="articleimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
