# Generated by Django 5.2.1 on 2026-09-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articleimage_options_articleimage_caption_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("plain", "Plain text"),
                    ("markdown", "Markdown"),
                    ("html", "Rich text HTML"),
                ],
                default="plain",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ArticleAutosave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=35)),
                ("subtitle", models.CharField(blank=True, max_length=50)),
                ("content", models.TextField(blank=True)),
                (
                    "content_format",
                    models.CharField(
                        choices=[
                            ("plain", "Plain text"),
                            ("markdown", "Markdown"),
                            ("html", "Rich text HTML"),
                        ],
                        default="plain",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True, max_length=500)),
                ("editor_state", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autosave",
                        to="articles.article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_autosaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
