# Generated by Django 5.2.1 on 2026-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_article_content_format_articleautosave"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="canonical_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="article",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/og-images/"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
