# Generated by Django 5.2.1 on 2026-09-30 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_moderationflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("gu", "Gujarati"),
                            ("mr", "Marathi"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ar", "Arabic"),
                        ],
                        max_length=5,
                    ),
                ),
                ("title", models.CharField(max_length=35)),
                ("subtitle", models.CharField(blank=True, max_length=50)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, max_length=500)),
                (
                    "content_format",
                    models.CharField(
                        choices=[
                            ("plain", "Plain text"),
                            ("markdown", "Markdown"),
                            ("html", "Rich text HTML"),
                        ],
                        default="plain",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="articles.article",
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["language_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "language_code"),
                        name="unique_article_translation_language",
                    )
                ],
            },
        ),
    ]
