# Generated by Django 5.1.3 on 2026-10-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_articletranslation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFactCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim", models.CharField(max_length=500)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partly_verified", "Partly verified"),
                            ("unverified", "Unverified"),
                            ("false", "False"),
                        ],
                        max_length=30,
                    ),
                ),
                ("explanation", models.TextField()),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_checks",
                        to="articles.article",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fact_checks_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=150)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary source"),
                            ("secondary", "Secondary source"),
                            ("reference", "Reference"),
                        ],
                        default="reference",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_sources_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "created_at"],
            },
        ),
    ]
