# Generated by Django 5.1.3 on 2026-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0019_articlemedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
