# Generated by Django 5.2.1 on 2026-10-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0025_contentexperiment_experimentassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
