# Generated by Django 5.2.1 on 2026-10-05 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0027_articleeditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleEngagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("session_key", models.CharField(blank=True, max_length=128)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("read_start", "Read started"),
                            ("read_progress", "Read progress"),
                            ("read_complete", "Read completed"),
                            ("share", "Shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_events",
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_engagement_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "event_type", "created_at"],
                        name="articles_ar_article_ab88e1_idx",
                    )
                ],
            },
        ),
    ]
