# Generated by Django 5.2.1 on 2026-10-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0029_editorialassistantrun"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleassignment",
            options={"ordering": ["-priority", "due_at", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="articleassignment",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articleassignment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="articleassignment",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="articleassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("review", "Review"),
                    ("blocked", "Blocked"),
                    ("done", "Done"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="articleassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
