# Generated by Django 5.2.1 on 2026-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0033_articletranslation_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemedia",
            name="captions_file",
            field=models.FileField(
                blank=True, null=True, upload_to="articles/captions/"
            ),
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="processing_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/media-thumbnails/"
            ),
        ),
    ]
